language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  api_key:
    secure: e89d24fb695a9f525dc880d187083c22780461b1
  app: ece-userapi
  on:
    repo: sergkudinov/ece-userapi
